on: [push]

name: CI

jobs:
  build_and_test:
    name: Codecrafters Redis Rust
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions/checkout@v2
      - name: Install Redis-cli
        run: |
          sudo apt-get update
          sudo apt-get install redis-server
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: |
          cargo test --verbose
          bash tests/run_all.sh
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings
      # - name: Install cargo-audit
      #   run: cargo install cargo-audit
      # - name: Audit
      #   run: cargo audit